/*
 * CATÁLOGO DE PRODUCTOS — JHONY HENAO
 *
 * Catálogo reconstruido a partir de las imágenes reales incluidas
 * en la carpeta imagenes. Cada fotografía de producto tiene su
 * propia referencia para que ninguna imagen quede sin producto.
 */
window.CATALOGO = {
  PRODUCTS: [
    {"id":1,"name":"Tapa cola SZR 150","variant":"Plata","price":70000,"image":"tapa-cola-plata.jpeg","images":["tapa-cola-plata.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapa cola","plata","szr 150"],"description":"Tapa cola para Yamaha SZR 150 en color plata."},
    {"id":2,"name":"Tapa cola SZR 150","variant":"Verde","price":70000,"image":"tapa-cola-verde.jpeg","images":["tapa-cola-verde.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapa cola","verde","szr 150"],"description":"Tapa cola para Yamaha SZR 150 en color verde."},
    {"id":3,"name":"Tapa cola SZR 150","variant":"Roja","price":70000,"image":"tapa-cola-roja.jpeg","images":["tapa-cola-roja.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapa cola","roja","szr 150"],"description":"Tapa cola para Yamaha SZR 150 en color roja."},
    {"id":4,"name":"Tapa cola SZR 150","variant":"Azul","price":70000,"image":"tapa-cola-azul.jpeg","images":["tapa-cola-azul.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapa cola","azul","szr 150"],"description":"Tapa cola para Yamaha SZR 150 en color azul."},
    {"id":5,"name":"Tapa cola SZR 150","variant":"Negra","price":70000,"image":"tapa-cola-negra.jpeg","images":["tapa-cola-negra.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapa cola","negra","szr 150"],"description":"Tapa cola para Yamaha SZR 150 en color negra."},
    {"id":6,"name":"Tapa cola SZR 150","variant":"Gris","price":70000,"image":"tapa-cola-gris.jpeg","images":["tapa-cola-gris.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapa cola","gris","szr 150"],"description":"Tapa cola para Yamaha SZR 150 en color gris."},
    {"id":7,"name":"Tapa cola SZR 150","variant":"Azul oscuro","price":70000,"image":"tapa-cola-azul-oscura.jpeg","images":["tapa-cola-azul-oscura.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapa cola","azul oscuro","szr 150"],"description":"Tapa cola para Yamaha SZR 150 en color azul oscuro."},
    {"id":8,"name":"Tapa cola SZR 150","variant":"Blanca","price":70000,"image":"tapa-cola-blanca.jpeg","images":["tapa-cola-blanca.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapa cola","blanca","szr 150"],"description":"Tapa cola para Yamaha SZR 150 en color blanca."},
    {"id":9,"name":"Soporte de parrilla SZR 150","variant":"Blanco","price":100000,"image":"cachos-szr-150-blanco.jpeg","images":["cachos-szr-150-blanco.jpeg"],"category":"Soportes","brands":["Yamaha"],"models":["SZR 150"],"tags":["soporte","parrilla","szr 150","blanco"],"description":"Soporte de parrilla para Yamaha SZR 150 en color blanco."},
    {"id":10,"name":"Soporte de parrilla SZR 150","variant":"Negro","price":100000,"image":"cachos-szr-150-negro.jpeg","images":["cachos-szr-150-negro.jpeg"],"category":"Soportes","brands":["Yamaha"],"models":["SZR 150"],"tags":["soporte","parrilla","szr 150","negro"],"description":"Soporte de parrilla para Yamaha SZR 150 en color negro."},
    {"id":11,"name":"Cachete lateral SZR 150","variant":"Azul","price":40000,"image":"cachetes-szr-150-1.jpeg","images":["cachetes-szr-150-1.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["cachete","lateral","szr 150","azul"],"description":"Cachete lateral para Yamaha SZR 150, variante azul."},
    {"id":12,"name":"Cachete lateral SZR 150","variant":"Plata","price":40000,"image":"cachetes-szr-150-2.jpeg","images":["cachetes-szr-150-2.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["cachete","lateral","szr 150","plata"],"description":"Cachete lateral para Yamaha SZR 150, variante plata."},
    {"id":13,"name":"Cachete lateral SZR 150","variant":"Negro","price":40000,"image":"cachetes-szr-150-3.jpeg","images":["cachetes-szr-150-3.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["cachete","lateral","szr 150","negro"],"description":"Cachete lateral para Yamaha SZR 150, variante negro."},
    {"id":14,"name":"Cachete lateral SZR 150","variant":"Azul oscuro","price":40000,"image":"cachetes-szr-150-4.jpeg","images":["cachetes-szr-150-4.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["cachete","lateral","szr 150","azul oscuro"],"description":"Cachete lateral para Yamaha SZR 150, variante azul oscuro."},
    {"id":15,"name":"Cachete lateral SZR 150","variant":"Negro mate","price":40000,"image":"cachetes-szr-150-5.jpeg","images":["cachetes-szr-150-5.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["cachete","lateral","szr 150","negro mate"],"description":"Cachete lateral para Yamaha SZR 150, variante negro mate."},
    {"id":16,"name":"Cachete lateral SZR 150","variant":"Rojo","price":40000,"image":"cachetes-szr-150-6.jpeg","images":["cachetes-szr-150-6.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["cachete","lateral","szr 150","rojo"],"description":"Cachete lateral para Yamaha SZR 150, variante rojo."},
    {"id":17,"name":"Cachete lateral SZR 150","variant":"Verde","price":40000,"image":"cachetes-szr-150-7.jpeg","images":["cachetes-szr-150-7.jpeg"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["cachete","lateral","szr 150","verde"],"description":"Cachete lateral para Yamaha SZR 150, variante verde."},
    {"id":18,"name":"Visor SZR 150","variant":"Rojo","price":30000,"image":"visor-szr-150-rojo.jpeg","images":["visor-szr-150-rojo.jpeg"],"category":"Visores","brands":["Yamaha"],"models":["SZR 150"],"tags":["visor","rojo","szr 150"],"description":"Visor para Yamaha SZR 150 en color o acabado rojo."},
    {"id":19,"name":"Visor SZR 150","variant":"Ahumado","price":30000,"image":"visor-szr-150-ahumado.jpeg","images":["visor-szr-150-ahumado.jpeg"],"category":"Visores","brands":["Yamaha"],"models":["SZR 150"],"tags":["visor","ahumado","szr 150"],"description":"Visor para Yamaha SZR 150 en color o acabado ahumado."},
    {"id":20,"name":"Visor SZR 150","variant":"Naranja","price":30000,"image":"visor-szr-150-naranja.jpeg","images":["visor-szr-150-naranja.jpeg"],"category":"Visores","brands":["Yamaha"],"models":["SZR 150"],"tags":["visor","naranja","szr 150"],"description":"Visor para Yamaha SZR 150 en color o acabado naranja."},
    {"id":21,"name":"Visor SZR 150","variant":"Azul","price":30000,"image":"visor-szr-150-azul.jpeg","images":["visor-szr-150-azul.jpeg"],"category":"Visores","brands":["Yamaha"],"models":["SZR 150"],"tags":["visor","azul","szr 150"],"description":"Visor para Yamaha SZR 150 en color o acabado azul."},
    {"id":22,"name":"Visor SZR 150","variant":"Morado","price":30000,"image":"visor-szr-150-morado.jpeg","images":["visor-szr-150-morado.jpeg"],"category":"Visores","brands":["Yamaha"],"models":["SZR 150"],"tags":["visor","morado","szr 150"],"description":"Visor para Yamaha SZR 150 en color o acabado morado."},
    {"id":23,"name":"Visor SZR 150","variant":"Negro","price":30000,"image":"visor-szr-150-negro.jpeg","images":["visor-szr-150-negro.jpeg"],"category":"Visores","brands":["Yamaha"],"models":["SZR 150"],"tags":["visor","negro","szr 150"],"description":"Visor para Yamaha SZR 150 en color o acabado negro."},
    {"id":24,"name":"Visor SZR 150","variant":"Transparente","price":30000,"image":"visor-szr-150-transparente.jpeg","images":["visor-szr-150-transparente.jpeg"],"category":"Visores","brands":["Yamaha"],"models":["SZR 150"],"tags":["visor","transparente","szr 150"],"description":"Visor para Yamaha SZR 150 en color o acabado transparente."},
    {"id":25,"name":"Juego de tapas de tanque SZR 150","variant":"Rojo","price":100000,"image":"tapas-tanque-szr-150-rojo.png","images":["tapas-tanque-szr-150-rojo.png"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapas de tanque","tanque","rojo","szr 150"],"description":"Juego de tapas de tanque para Yamaha SZR 150 en color rojo."},
    {"id":26,"name":"Juego de tapas de tanque SZR 150","variant":"Negro","price":100000,"image":"tapas-tanque-szr-150-negro.png","images":["tapas-tanque-szr-150-negro.png"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapas de tanque","tanque","negro","szr 150"],"description":"Juego de tapas de tanque para Yamaha SZR 150 en color negro."},
    {"id":27,"name":"Juego de tapas de tanque SZR 150","variant":"Gris","price":100000,"image":"tapas-tanque-szr-150-gris.png","images":["tapas-tanque-szr-150-gris.png"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapas de tanque","tanque","gris","szr 150"],"description":"Juego de tapas de tanque para Yamaha SZR 150 en color gris."},
    {"id":28,"name":"Juego de tapas de tanque SZR 150","variant":"Blanco","price":100000,"image":"tapas-tanque-szr-150-blanco.png","images":["tapas-tanque-szr-150-blanco.png"],"category":"Tapas","brands":["Yamaha"],"models":["SZR 150"],"tags":["tapas de tanque","tanque","blanco","szr 150"],"description":"Juego de tapas de tanque para Yamaha SZR 150 en color blanco."},
    {"id":29,"name":"Guardabarros delantero SZR 150","variant":"Azul","price":60000,"image":"guardabarros-szr-150-azul.jpg","images":["guardabarros-szr-150-azul.jpg"],"category":"Guardabarros","brands":["Yamaha"],"models":["SZR 150"],"tags":["guardabarros","delantero","szr 150","azul"],"description":"Guardabarros delantero para Yamaha SZR 150 en color azul."},
    {"id":30,"name":"Guardabarros delantero SZR 150","variant":"Rojo","price":60000,"image":"guardabarros-szr-150-rojo.png","images":["guardabarros-szr-150-rojo.png"],"category":"Guardabarros","brands":["Yamaha"],"models":["SZR 150"],"tags":["guardabarros","delantero","szr 150","rojo"],"description":"Guardabarros delantero para Yamaha SZR 150 en color rojo."},
    {"id":31,"name":"Guardabarros delantero SZR 150","variant":"Plata","price":60000,"image":"guardabarros-szr-150-plata.jpg","images":["guardabarros-szr-150-plata.jpg"],"category":"Guardabarros","brands":["Yamaha"],"models":["SZR 150"],"tags":["guardabarros","delantero","szr 150","plata"],"description":"Guardabarros delantero para Yamaha SZR 150 en color plata."},
    {"id":32,"name":"Guardabarros delantero SZR 150","variant":"Gris","price":60000,"image":"guardabarros-szr-150-gris.jpg","images":["guardabarros-szr-150-gris.jpg"],"category":"Guardabarros","brands":["Yamaha"],"models":["SZR 150"],"tags":["guardabarros","delantero","szr 150","gris"],"description":"Guardabarros delantero para Yamaha SZR 150 en color gris."},
    {"id":33,"name":"Guardabarros delantero SZR 150","variant":"Blanco","price":60000,"image":"guardabarros-szr-150-blanco.png","images":["guardabarros-szr-150-blanco.png"],"category":"Guardabarros","brands":["Yamaha"],"models":["SZR 150"],"tags":["guardabarros","delantero","szr 150","blanco"],"description":"Guardabarros delantero para Yamaha SZR 150 en color blanco."},
    {"id":34,"name":"Guardabarros delantero SZR 150","variant":"Verde","price":60000,"image":"guardabarros-szr-150-verde.png","images":["guardabarros-szr-150-verde.png"],"category":"Guardabarros","brands":["Yamaha"],"models":["SZR 150"],"tags":["guardabarros","delantero","szr 150","verde"],"description":"Guardabarros delantero para Yamaha SZR 150 en color verde."},
    {"id":35,"name":"Guardabarros delantero SZR 150","variant":"Negro","price":60000,"image":"guardabarros-szr-150-negro.png","images":["guardabarros-szr-150-negro.png"],"category":"Guardabarros","brands":["Yamaha"],"models":["SZR 150"],"tags":["guardabarros","delantero","szr 150","negro"],"description":"Guardabarros delantero para Yamaha SZR 150 en color negro."},
    {"id":36,"name":"Cachos para parrilla BWS FI","variant":"Plata","price":110000,"image":"cachos-parrilla-bws-fi-plata.jpg","images":["cachos-parrilla-bws-fi-plata.jpg"],"category":"Soportes","brands":["Yamaha"],"models":["BWS FI"],"tags":["cachos","parrilla","bws fi","plata"],"description":"Cachos para parrilla de Yamaha BWS FI, acabado plata."},
    {"id":37,"name":"Cachos para parrilla BWS FI","variant":"Negro","price":110000,"image":"cachos-parrilla-bws-fi-negro.jpg","images":["cachos-parrilla-bws-fi-negro.jpg"],"category":"Soportes","brands":["Yamaha"],"models":["BWS FI"],"tags":["cachos","parrilla","bws fi","negro"],"description":"Cachos para parrilla de Yamaha BWS FI, acabado negro."},
    {"id":38,"name":"Cachos para parrilla BWS FI","variant":"Plata 2","price":110000,"image":"cachos-parrilla-bws-fi-plata-2.jpg","images":["cachos-parrilla-bws-fi-plata-2.jpg"],"category":"Soportes","brands":["Yamaha"],"models":["BWS FI"],"tags":["cachos","parrilla","bws fi","plata 2"],"description":"Cachos para parrilla de Yamaha BWS FI, acabado plata 2."},
    {"id":39,"name":"Carenaje delantero SZR 150","variant":"","price":40000,"image":"carenaje-szr-150-.jpg","images":["carenaje-szr-150-.jpg"],"category":"Carenajes","brands":["Yamaha"],"models":["SZR 150"],"tags":["carenaje","delantero","szr 150"],"description":"Carenaje delantero para Yamaha SZR 150."},
    {"id":40,"name":"Protector de mofle SZR 150","variant":"Redondo","price":20000,"image":"protector-mofle-szr.JPG","images":["protector-mofle-szr.JPG"],"category":"Protectores","brands":["Yamaha"],"models":["SZR 150"],"tags":["protector","mofle","redondo","szr 150"],"description":"Protector de mofle pequeño, con estructura redonda, en plástico negro."},
    {"id":41,"name":"Protector de mofle SZR 150","variant":"Largo","price":30000,"image":"protector-mofle-trasero szr.jpg","images":["protector-mofle-trasero szr.jpg"],"category":"Protectores","brands":["Yamaha"],"models":["SZR 150"],"tags":["protector","mofle","largo","szr 150"],"description":"Protector de mofle largo o alargado, en plástico negro."},
    {"id":42,"name":"Visor NMAX V1","variant":"Varios colores y acabados","price":70000,"image":"visor-nmax-v1-ahumado.jpg","images":["visor-nmax-v1-ahumado-2.jpg","visor-nmax-v1-ahumado.jpg","visor-nmax-v1-amarillo.jpg","visor-nmax-v1-azul.jpg","visor-nmax-v1-camaleon.jpg","visor-nmax-v1-morado-2.jpg","visor-nmax-v1-morado.jpg","visor-nmax-v1-naranja-2.jpg","visor-nmax-v1-naranja.jpg","visor-nmax-v1-negro-mate.jpg","visor-nmax-v1-rojo.jpg","visor-nmax-v1-transparente.jpg"],"category":"Visores","brands":["Yamaha"],"models":["NMAX V1"],"tags":["visor","nmax v1","yamaha"],"description":"Visor para Yamaha NMAX V1. Disponible en diferentes colores y acabados. Precio: $70.000."},
  ]
};
